### ISSUE TITLE
Add Tags button not working

### ISSUE THREAD

**Issue by goldstar1x** [cc1234475/stashtag#1]
Just tried stashtag, it works great up until it displays the window with images and tags to be added, then when I press 'Add Tags', it doesn't do anything. 

I can change the values in the dropdown list, hit the X button to remove the tags. Cancel works, everything seems to work except for Add Tags

When I open the console, after pressing the button I get:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at create_tag (userscript.html?name=stashtag.user.js&id=baf76dd0-935b-4a31-b0b6-5a8c2fdf8384:1241:34)
    at async HTMLButtonElement.<anonymous> (userscript.html?name=stashtag.user.js&id=baf76dd0-935b-4a31-b0b6-5a8c2fdf8384:1210:30)
```

My stash version: 

v0.20.0-3-ga6ef924d
Build hash:
a6ef924d

Browser:
Chrome Version 112.0.5615.49 (Official Build) (64-bit)

**Comment by cc1234475** [comment]
Hi @goldstar1x, I just tried it on chrome `112.0.5615.49` and it worked for me.
From the error it looks to be related to tag creation, I suspect it's failing to create a tag due to aliases. possibly capitalisation.

**Comment by cc1234475** [comment]
Would you be able to check the post request going to the `/graphql` while hitting the add tags and see if we can see what stash is returning as an error?

**Comment by goldstar1x** [comment]
hmm pretty strange, I tried it again just now, and suddenly it's all working fine... I didn't do anything differently other than trying it on a different scene, cant remember which scenes I tried it with before but it was more than 1 so probably isn't because of the scene. anyway, will close this for now and see if it happens again. thanks!
